# Application Configuration
app:
  name: "Multi-Agent Dialogue Simulator"
  version: "1.0.0"
  debug: false

# Model Configuration
model:
  default_model: "teknium/OpenHermes-2.5-Mistral-7B"
  fallback_models:
    - "microsoft/DialoGPT-medium"
    - "facebook/blenderbot-400M-distill"
  
  # Generation parameters
  generation:
    max_length: 512
    temperature: 0.7
    top_p: 0.9
    repetition_penalty: 1.1
    do_sample: true

# Memory Configuration
memory:
  embedding_model: "all-MiniLM-L6-v2"
  max_conversation_history: 50
  max_episodic_memories: 1000
  max_semantic_memories: 500
  memory_decay_rate: 0.95
  importance_threshold: 0.3

# Agent Configuration
agents:
  reflection_frequency: 3  # Reflect every N turns
  emotion_update_rate: 0.1
  relationship_update_rate: 0.05
  max_goals: 5
  max_beliefs: 20

# Simulation Configuration
simulation:
  max_conversation_length: 100
  auto_advance_phases: false
  intervention_cooldown: 2  # turns
  performance_tracking: true

# UI Configuration
ui:
  theme: "light"
  max_agents_display: 5
  conversation_display_limit: 20
  auto_scroll: true
  show_analytics: true
  show_debug_info: false

# Logging Configuration
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/simulator.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5

# Export Configuration
export:
  default_format: "json"
  include_memory_data: true
  include_analytics: true
  compress_exports: true
